title: Тут і зараз
baseURL: /
params:
  layout_style: overflow
  palette: blue
  header:
    title: Тут і зараз
    tagline: Header Tagline
    profile_img: images/zen.png
    bg: dark
    has_nav: true
    has_social: true
  footer:
    content: '&copy; All rights reserved.'
    links:
      - text: Зроблено з любов’ю
        url: 'https://www.facebook.com/osvichena'
        new_window: true
disableKinds:
  - RSS
  - taxonomy
  - taxonomyTerm
